config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"
  get "/", to: "posts#index"
  post "/", to: "posts#create"

  resources :posts, only: [:edit, :update, :destroy]

  get "signup", to: "users#new"
  post "signup", to: "users#create"

  get "users", to: "users#index"
  get "friends", to: "users#show"
  delete "friends", to: "friendships#destroy"


  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  delete "signout", to: "sessions#destroy"


  resources :friendships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :friend_id, uniqueness: { scope: :user_id }
  #validates each friend_id and the user_id in the friendship is unique
  #this avoids adding the same user as friend multiple times
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user#, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :email, :name
  has_secure_password

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :posts

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  validates_format_of :email, :with => /.+@.+\..+/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :fetch_user

  private

  def fetch_user
    @current_user = User.find_by_id(session[:user_id])
  end

  def authenticate_user
    if @current_user.nil?
      flash[:error] = "Access denied"
      return redirect_to root_path
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = @current_user.friendships.new(:friend_id => params[:friend_id])
    if @friendship.save
      redirect_to root_path
      flash[:success] = "Successfully added a friend."
    else
      redirect_to users_path
      flash[:error] = "Failed to add friend."
    end
  end

  def destroy
    @friendship = @current_user.friendships.find(params[:id]).destroy
    redirect_to root_path
    flash[:success] = "Successfully removed a friend."
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, only: [:create]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def create
    @post = Post.new(clean_params)
    # @post = @current_user
    @post.user_id = @current_user.id
    @post.username = @current_user.name
    if @post.save
      redirect_to root_path
      flash[:success] = "Your post is created."
    else
      redirect_to root_path
      flash[:error] = "Fatal error."
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    # @post.user_id = @current_user.id
    # @post.username = @current_user.name
    @post.update_attributes(update_params)
    if @post.save
      redirect_to root_path
      flash[:success] = "Your post is updated."
    else
      redirect_to root_path
      flash[:error] = "Fatal error."
    end
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    redirect_to root_path
    flash[:success] = "Your post is deleted."
  end

  private

  def clean_params
    params.permit(:message, :image, :video, :username)
  end

  def update_params
    params.require(:post).permit(:message, :image, :video, :username)
  end

end

# post.errors.full_messages to check full error messages

# ADDITIONAL FEATURES YOU SHOULD PROBABLY ADD LATER ON
# => set parameters for URL links
#   -> If they render nothing, don't post them and flash an error notice

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
      flash[:success] = "You have successfully signed in."
    else
      redirect_to signin_path
      flash[:error] = "Invalid email/password."
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(clean_params)
    if @user.save
      redirect_to signin_path
      flash[:success] = "You have successfully signed up."
    else
      redirect_to signup_path
      flash[:error] = "Try another Email or Username."
    end
  end

  private

  def clean_params
    params.permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
      %Q{<iframe title="YouTube video player" width="640" height="390" src="https://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
    elsif
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
      %Q{<iframe title="YouTube video player" width="640" height="390" src="https://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
    end
    # RESEARCH AND UNDERSTAND THE REGEX (REGULAR EXPRESSION) USED HERE
  end

end

app/views/includes/_flash_notices.html.erb
<div class="ui main text container notices">
  <% if flash %>
    <% flash.each do |k,v| %>
      <div class="ui message transition <%= k.to_s %>">
        <i class="close icon"></i>
        <div class="header">
          <%= k.to_s.capitalize %>
        </div>
        <p><%= v %></p>
      </div>
    <%end%>
    <% flash.clear %>
  <%end%>
</div>

app/views/includes/_footer.html.erb
<div class="ui inverted vertical footer segment orange">
  <div class="ui center aligned container">

    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="#">Site Map</a>
      <a class="item" href="#">Contact Us</a>
      <a class="item" href="#">Terms and Conditions</a>
      <a class="item" href="#">Privacy Policy</a>
    </div>
    <p class="copyright">© Copyright Kevin HW Li 2017</p>
  </div>
</div>

app/views/includes/_form_errors.html.erb
<!-- <% if form.object.errors.messages.present? %>
  <div class="ui message transition error">
    <div class="header">Please resolve:</div>
    <ul>
      <% form.object.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <%end%>
    </ul>
  </div>
<%end%> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>postSome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- <%= cloudinary_js_config %> -->
  </head>

  <body>
    <div class="ui inverted segment orange">
      <div class="ui inverted pointing menu orange">
        <%= link_to "Home", root_path, class: "item home" %>
        <% if @current_user %>
          <%= link_to "Friends", friends_path, class: "item" %>
        <%end%>
        <div class="right item">
          <% if @current_user %>
            <%= link_to "Sign out", signout_path, method: "delete", class: "ui inverted button" %>
          <%else%>
            <%= link_to "Sign up", signup_path, class: "ui inverted button" %>
            <%= link_to "Sign in", signin_path, class: "ui inverted button" %>
          <%end%>
        </div>
      </div>
    </div>
    <% if @current_user %>
      <p class="signin_user_text">Signed in as: <%= @current_user.name %></p>
    <%end%>
    <%= render "includes/flash_notices" %>
    <%= yield %>
    <%= render "includes/footer" %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="ui main text container">
  <%= form_for @post, :html => {:class => 'ui form'} do |f| %>
  <p>
    <%= f.label :message %>
    <%= f.text_field :message %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.text_field :image, :placeholder => "Add an image URL" %>
  </p>
  <p>
    <%= f.label :video %>
    <%= f.text_field :video, :placeholder => "Add a Youtube URL" %>
  </p>
    <%= f.submit "Edit post", :class => 'ui button orange' %>
  <%end%>
</div>

app/views/posts/index.html.erb
<% if !@current_user %>
  <div class="ui inverted vertical masthead center aligned segment orange">

      <h1 class="ui inverted header">
        Join the Community
      </h1>
      <h2>Share whatever you want when you want to.</h2>
      <div class="ui huge primary button"><%= link_to "Get started", signup_path, class: "start" %> <i class="right arrow icon"></i></div>
    </div>

  </div>

<% end %>

<% if @current_user %>

<div class="ui main text container pushable">
  <%= form_tag "/", method: "post", class: "ui form" do %>

    <p>
      <label>Message</label>
      <input type="text" name="message" placeholder="What's happening?"/>
    </p>
    <p>
      <label>Image</label>
      <input type="text" name="image" placeholder="Add an image URL"/>
    </p>
    <p>
      <label>Youtube</label>
      <input type="text" name="video" placeholder="Add a Youtube URL"/>
    </p>
    <p>
      <input type="submit" value="Post" class="ui button orange"/>
    </p>


  <% end %>

  <% @posts.each do |p| %>
    <div class="ui piled segment feed">

        <div class="event">
          <div class="content">
            <div class="summary">
              <a class="user">
                <%= p.username %>
              </a> posted
              <div class="date">
                <%= "#{time_ago_in_words(p.created_at.in_time_zone("Sydney"))} ago" %>
              </div>
            </div>
            <div class="extra text">
              <p><%= p.message %></p>
              <img src="<%= p.image %>"/>
              <p><%= raw(youtube_embed("#{p.video}")) %></p>
            </div>
            <div class="meta">
              <% if @current_user %>
                <% if @current_user.name == p.username %>
                  <%= link_to "edit", edit_post_path(p), class: "mini ui basic button orange" %>
                  <%= link_to "delete", post_path(p), method: :delete, class: "mini ui basic button orange" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
    </div>
  <% end %>


</div>

<% end %>

app/views/users/index.html.erb
<div class="ui main text container">
  <h1>List of users</h1>

  <% @users.each do |u| %>
    <% if u != @current_user %>
      <p><%= u.name %> <%= link_to "add", friendships_path(:friend_id => u), :method => :post, class: "mini ui basic button orange" %></p>
    <%end%>
  <%end%>
</div>

app/views/users/new.html.erb
<div class="ui main text container">
  <h1 class="signup">Sign up</h1>

  <%= form_tag "/signup", method: "post", class: "ui form" do %>
    <div class="field">
      <label>Username</label>
      <input type="text" name="name" placeholder="Username">
    </div>
    <div class="field">
      <label>Email</label>
      <input type="text" name="email" placeholder="Email">
    </div>
    <div class="field">
      <label>Password</label>
      <input type="password" name="password" placeholder="Password">
    </div>
    <div class="field">
      <div class="ui checkbox">
        <input type="checkbox" tabindex="0">
        <label>I agree to the Terms and Conditions</label>
      </div>
    </div>
    <p>
      <input type="submit" value="Sign up" class="ui button orange">
    </p>

  <%end%>
</div>

app/views/users/show.html.erb
<div class="ui main text container">
  <h1>Your friends</h1>

  <% @current_user.friendships.each do |friendship| %>
    <p><%= friendship.friend.name %> <%= link_to "remove", friendship, :method => :delete, class: "mini ui basic button orange"%></p>
  <%end%>

  <p> <%= link_to "Find Friends", users_path, class: "ui button orange"%> </p>

  <h1>People befriended you</h1>
  <% @current_user.inverse_friends.each do |i| %>
    <p><%= i.name %></p>
  <%end%>
</div>